spring.application.name=eventhub
spring.datasource.url=jdbc:mysql://localhost:3306/eventhub
spring.datasource.username:root
spring.datasource.password:MySql@8
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=MySuperSecretKeyForEventHubApplication2026MySuperSecretKey
jwt.expiration=86400000

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-unknown-properties=false

razorpay.key.id=rzp_test_Sze4fHMj9CBgdQ
razorpay.key.secret=guv6kXsL7Xtm4RWUlrDRgnTy